/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JLabel;

/**
 *
 * @author santi
 */
public class Administrador extends javax.swing.JFrame {
    public String nombre_emple;
    public static int sesion_usuario;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        
        sesion_usuario=1;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administrador");
        setSize(650,430);
        setResizable(false);
        //esto es el wallpaper o fondo que es utilizado por un jlabel
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(label_Fondo.getWidth(), label_Fondo.getHeight(), Image.SCALE_DEFAULT));
        label_Fondo.setIcon(wall);
        //esto es para poner el nombre de usuario en el letrero bienvenido
        repaint();try {
            Connection cn = Conexion.conectar();
            String user = Login.user;
            //esto es la conexion con la base de datos
            PreparedStatement pst = cn.prepareStatement("select nombre_empleado from empleados where username = '" + 
                     user + "'");
            ResultSet rs = pst.executeQuery();
            
            
            if (rs.next()) {
                nombre_emple =rs.getString("nombre_empleado");
                jLabel_bienvenida.setText("Bienvenido " + nombre_emple);
            }
        } catch (SQLException e) {
            System.err.println("error el la interfaz de Administrador");
        }
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_bienvenida = new javax.swing.JLabel();
        boton_registro = new javax.swing.JButton();
        boton_gest = new javax.swing.JButton();
        boton_creatividad = new javax.swing.JButton();
        boton_acerca = new javax.swing.JButton();
        Boton_cap = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_bienvenida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 30));

        boton_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        boton_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registroActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        boton_gest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        boton_gest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gestActionPerformed(evt);
            }
        });
        getContentPane().add(boton_gest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 100));

        boton_creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        boton_creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(boton_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 120, 100));

        boton_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geekipedia.png"))); // NOI18N
        boton_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_acercaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_acerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 100));

        Boton_cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        Boton_cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_capActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 100));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tecnico.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 120, 100));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creatividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Acerca de");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interfaz Tecnico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Interfaz Capturista");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel7.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));
        getContentPane().add(label_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_creatividadActionPerformed
        new Creatividad().setVisible(true);
    }//GEN-LAST:event_boton_creatividadActionPerformed

    private void boton_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registroActionPerformed
        new Registro_Usuario().setVisible(true);
    }//GEN-LAST:event_boton_registroActionPerformed

    private void boton_gestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gestActionPerformed
        new Admin_Usuarios().setVisible(true);
    }//GEN-LAST:event_boton_gestActionPerformed

    private void Boton_capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_capActionPerformed
        new Capturista().setVisible(true);
    }//GEN-LAST:event_Boton_capActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Tecnico().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void boton_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_acercaActionPerformed
        new Acerca_de().setVisible(true);
    }//GEN-LAST:event_boton_acercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_cap;
    private javax.swing.JButton boton_acerca;
    private javax.swing.JButton boton_creatividad;
    private javax.swing.JButton boton_gest;
    private javax.swing.JButton boton_registro;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_bienvenida;
    private javax.swing.JLabel label_Fondo;
    // End of variables declaration//GEN-END:variables

}
