/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author santi
 */
public class CambiarContraseña extends javax.swing.JFrame {
    String contranueva,contraconfir;
    String ID = InformacionEmpleado.ID;
    /**
     * Creates new form CambiarContraseña
     */
    public CambiarContraseña() {
        initComponents();
        setResizable(false);
        setSize(350,230);
        setTitle("Restablecer Password");
        setLocationRelativeTo(null);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(Label_wall.getWidth(), Label_wall.getHeight(), Image.SCALE_DEFAULT));
        Label_wall.setIcon(wall);
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boton_confirmar = new javax.swing.JButton();
        pass_nueva = new javax.swing.JPasswordField();
        pass_confirm = new javax.swing.JPasswordField();
        Label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambiar Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirma tu contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        boton_confirmar.setBackground(new java.awt.Color(153, 153, 255));
        boton_confirmar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_confirmar.setForeground(new java.awt.Color(255, 255, 255));
        boton_confirmar.setText("Cambiar Contraseña");
        boton_confirmar.setBorder(null);
        boton_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 30));

        pass_nueva.setBackground(new java.awt.Color(153, 153, 255));
        pass_nueva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_nueva.setForeground(new java.awt.Color(255, 255, 255));
        pass_nueva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pass_nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, -1));

        pass_confirm.setBackground(new java.awt.Color(153, 153, 255));
        pass_confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_confirm.setForeground(new java.awt.Color(255, 255, 255));
        pass_confirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pass_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 20));
        getContentPane().add(Label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_confirmarActionPerformed
        contranueva = pass_nueva.getText().trim();
        contraconfir = pass_confirm.getText().trim();
        
        if(contranueva.equals(contraconfir)){
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "update empleados set password =? where id_empleado = '"+ID+"'");
                pst.setString(1, contranueva);
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Su contraseña se cambio correctamente");
                dispose();
            } catch (SQLException e) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden","Error",JOptionPane.ERROR_MESSAGE);
            pass_nueva.setText("");
            pass_confirm.setText("");
        }
    }//GEN-LAST:event_boton_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_wall;
    private javax.swing.JButton boton_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pass_confirm;
    private javax.swing.JPasswordField pass_nueva;
    // End of variables declaration//GEN-END:variables
}
