/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author santi
 */
public class Gestionar_Clientes extends javax.swing.JFrame {
    public static String user_update = "";
    DefaultTableModel model = new DefaultTableModel();
    String ID_cliente;
    /**
     * Creates new form Gestionar_Clientes
     */
    public Gestionar_Clientes() {
        initComponents();
        setSize(630, 300);
        setLocationRelativeTo(null);
        setTitle("Gestionar Clientes");
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(), Image.SCALE_DEFAULT));
        label_wall.setIcon(wall);
        //esto lo que permite es que se muestre la informacion de los clioentes en la tabla
        
        try {
            Connection cn = Conexion.conectar();
            //esto pide los datos que se van a poner en la tabla 
            PreparedStatement pst = cn.prepareStatement("select id_cliente, nombre_cliente, email_cliente, tel_cliente, dir_cliente from clientes");
        ResultSet rs =pst.executeQuery();
        //esto configura la tabla para que se muestre la informacion en los diferentes campos
        jTable_Clientes =new JTable(model);
        jScrollPane1.setViewportView(jTable_Clientes);
        
        model.addColumn(" ");
        model.addColumn("Nombre");
        model.addColumn("email");
        model.addColumn("telefono");
        model.addColumn("direccion");
        
        //esto lo que permite es que se ingrese la informacion en la tabla
            while (rs.next()) {                
                //esto dice que mientras i< a el numero de columnas de la tabla entonces que vaya ingresando la informacion
                Object[] fila= new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                //y esto es para que cuando termine de ingresar la informacion pase a la siguiente y si se cumpla condicion
                //que es que si hay mas datos los ponga en esta nueva fila
                model.addRow(fila);
            }
            cn.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar la informacion", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //este codigo lo que permite es que capture en donde el mouse dio click para mostrar la informacion de ese cliente
        jTable_Clientes.addMouseListener(new MouseAdapter() {
            @Override
        public void mouseClicked(MouseEvent e){
            int fila_point = jTable_Clientes.rowAtPoint(e.getPoint());
            int columna_point =1;
            if (fila_point>-1) {
                user_update =(String)model.getValueAt(fila_point, columna_point);
                    new InformacionCliente().setVisible(true);
            }
        }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Clientes = new javax.swing.JTable();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel2.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Clientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 190));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestionar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestionar_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Clientes;
    private javax.swing.JLabel label_wall;
    // End of variables declaration//GEN-END:variables
}
