/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static ventanas.InformacionCliente.equipo;

/**
 *
 * @author santi
 */
public class Gestion_Equipos extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    public static int seleccion;
    public static int capturista;
    
    /**
     * Creates new form Gestion_Equipos
     */
    public Gestion_Equipos() {
        initComponents();
        setResizable(false);
        setSize(600,400);
        setLocationRelativeTo(null);
        setTitle("Gestion de equipos");
        ImageIcon wall = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon paper = new ImageIcon(wall.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(), Image.SCALE_DEFAULT));
        label_wall.setIcon(paper);
        capturista = 0;
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_equipo, tipo_equipo, marca, estatus from equipo");
            ResultSet rs = pst.executeQuery();
            tabla_equipos = new JTable(model);
            jScrollPane1.setViewportView(tabla_equipos);
            model.addColumn(" ");
            model.addColumn("Tipo");
            model.addColumn("marca");
            model.addColumn("Estatus");
            while (rs.next()) {                
                Object[] fila =new Object[4];
                for (int i = 0; i < 4; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                model.addRow(fila);
            }
            cn.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener los datos de la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        tabla_equipos.addMouseListener(new MouseAdapter() {
            @Override
        public void mouseClicked(MouseEvent e){
            int fila_point = tabla_equipos.rowAtPoint(e.getPoint());
            int columna_point = 0;
            if (fila_point>-1) {
                equipo =(int)model.getValueAt(fila_point, columna_point);
                    new Informacion_equipo().setVisible(true);
                    
            }
        }
        });
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_equipos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        box_tipos = new javax.swing.JComboBox<>();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipos Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        tabla_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_equipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 600, 240));

        jLabel2.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        box_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo Ingreso", "No reparado", "En revision", "Reparado", "Entregado" }));
        box_tipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                box_tiposItemStateChanged(evt);
            }
        });
        getContentPane().add(box_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, -1));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_tiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_box_tiposItemStateChanged
        String selec = box_tipos.getSelectedItem().toString();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tabla_equipos.setRowSorter(tr);
        if (!selec.equals("Todos")) {
            tr.setRowFilter(RowFilter.regexFilter(selec));
        }else{
            tabla_equipos.setRowSorter(tr);
        }
    }//GEN-LAST:event_box_tiposItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_tipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_wall;
    private javax.swing.JTable tabla_equipos;
    // End of variables declaration//GEN-END:variables
}
