/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author santi
 */
public class Informacion_equipo extends javax.swing.JFrame {
    registrar_equipo mensajero = new registrar_equipo();
    String cliente = mensajero.nombre;
    int cap;
    String id_cliente = InformacionCliente.id_cliente;
    int id_equipo = InformacionCliente.equipo;
    String dia, mes, annio;
    /**
     * Creates new form Informacion_equipo
     */
    public Informacion_equipo() {
        cap = Gestion_Equipos.capturista;
        initComponents();
        setSize(660,520);
        setLocationRelativeTo(null);
        setTitle("Informacion Equipo de "+ Gestionar_Clientes.user_update);
        setResizable(false);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(), Image.SCALE_DEFAULT));
        label_wall.setIcon(wall);
        txt_nombre.setEnabled(false);
        txt_modificado.setEnabled(false);
        txt_fecha.setEnabled(false);
        
        txt_nombre.setText(Gestionar_Clientes.user_update);
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso, anno_ingreso, observaciones,"
         + " estatus, ultima_modificacion, comentarios_tecnico from equipo where id_equipo = '"+ id_equipo +"'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                box_tipos.setSelectedItem(rs.getString("tipo_equipo"));
                box_marcas.setSelectedItem(rs.getString("marca"));
                txt_modelo.setText(rs.getString("modelo"));
                txt_serie.setText(rs.getString("num_serie"));
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("anno_ingreso");
                txt_fecha.setText(dia+" del " + mes + " del año " +annio);
                area_capturista.setText(rs.getString("observaciones"));
                box_estatus.setSelectedItem(rs.getString("estatus"));
                txt_modificado.setText(rs.getString("ultima_modificacion"));
                area_tecnico.setText(rs.getString("comentarios_tecnico"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener la informacion de la base de datos","Error",JOptionPane.ERROR_MESSAGE);
        }
        if (cap == 1) {
            area_capturista.setEditable(true);
            area_tecnico.setEditable(false);
        }else{
            area_capturista.setEditable(false);
            area_tecnico.setEditable(true);
        }
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        box_tipos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        box_marcas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        box_estatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_capturista = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_tecnico = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_modificado = new javax.swing.JTextField();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del Equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Equipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        box_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laptop", "desktop", "impresora", "multifuncional" }));
        getContentPane().add(box_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        box_marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "acer", "brother", "samsung", "epson" , "hp", "toshiba", "lg", "apple", "alienware", "Asus", "Dell", "Xerox"}));
        getContentPane().add(box_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txt_serie.setBackground(new java.awt.Color(153, 153, 255));
        txt_serie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_serie.setForeground(new java.awt.Color(255, 255, 255));
        txt_serie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        jLabel7.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel8.setText("Fecha de Ingreso");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        txt_fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 190, 30));

        jLabel9.setText("Estatus:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        box_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo Ingreso", "No reparado", "En revision", "Reparado", "Entregado" }));
        getContentPane().add(box_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 90, 30));

        jLabel10.setText("Daño reportado y observaciones:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        area_capturista.setColumns(20);
        area_capturista.setRows(5);
        jScrollPane1.setViewportView(area_capturista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 136, 330, 110));

        jLabel11.setText("Comentarios y actualizacion del Tecnico:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        area_tecnico.setColumns(20);
        area_tecnico.setRows(5);
        jScrollPane2.setViewportView(area_tecnico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 266, 330, 120));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar Equipo");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 200, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ultima modificacion por:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        txt_modificado.setBackground(new java.awt.Color(153, 153, 255));
        txt_modificado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_modificado.setForeground(new java.awt.Color(255, 255, 255));
        txt_modificado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 30));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tipo,marca,modelo,num_serie,observaciones,tecnico,estatus;
        tipo = box_tipos.getSelectedItem().toString().trim();
        marca = box_marcas.getSelectedItem().toString().trim();
        modelo = txt_modelo.getText().trim();
        num_serie = txt_serie.getText().trim();
        observaciones = area_capturista.getText().trim();
        tecnico = area_tecnico.getText().trim();
        estatus =box_estatus.getSelectedItem().toString().trim();
        
        if (!modelo.isEmpty()&&!num_serie.isEmpty()) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                "update equipo set tipo_equipo = ?, marca = ?,modelo=?,num_serie = ?, observaciones = ?, estatus =?,"
              + "ultima_modificacion=?, comentarios_tecnico = ? where id_equipo = '"+id_equipo+"'");
                pst.setString(1, tipo);
                pst.setString(2, marca);
                pst.setString(3, modelo);
                pst.setString(4, num_serie);
                pst.setString(5, observaciones);
                pst.setString(6, estatus);
                pst.setString(7, Login.user);
                pst.setString(8, tecnico);
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Actualizacion Exitosa");
                dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error de conexion con la base de datos", "error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (modelo.isEmpty()) {
                txt_modelo.setBackground(Color.red);
            }if(num_serie.isEmpty()){
                txt_serie.setBackground(Color.red);
            }
            JOptionPane.showMessageDialog(null, "Rellena todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_equipo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_capturista;
    private javax.swing.JTextArea area_tecnico;
    private javax.swing.JComboBox<String> box_estatus;
    private javax.swing.JComboBox<String> box_marcas;
    private javax.swing.JComboBox<String> box_tipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_wall;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_modificado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_serie;
    // End of variables declaration//GEN-END:variables

    
}
