/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static ventanas.Gestion_Equipos.capturista;

/**
 *
 * @author santi
 */
public class InformacionCliente extends javax.swing.JFrame {
    int validacion;
    String nombre,mail,telefono,direcion;
    public static String  id_cliente;
    DefaultTableModel model = new DefaultTableModel();
    
    
    public static int equipo;
    
    /**
     * Creates new form InformacionCliente
     */
    public InformacionCliente() {
        
        initComponents();
        setSize(630,440);
        setLocationRelativeTo(null);
        setTitle("Informacion del Cliente "+Gestionar_Clientes.user_update);
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        txt_ultimo.setEnabled(false);
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(), Image.SCALE_DEFAULT));
        label_wall.setIcon(wall);
        label_titulo.setText("Informacion Del Cliente "+Gestionar_Clientes.user_update);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select id_cliente, nombre_cliente, email_cliente, tel_cliente, dir_cliente, ultima_modificacion from clientes where nombre_cliente = '"
            +Gestionar_Clientes.user_update +"'");
            ResultSet st = pst.executeQuery();
            if (st.next()) {
                id_cliente = st.getString("id_cliente");
                txt_nombre.setText(st.getString("nombre_cliente"));
                txt_email.setText(st.getString("email_cliente"));
                txt_telefono.setText(st.getString("tel_cliente"));
                txt_direccion.setText(st.getString("dir_cliente"));
                txt_ultimo.setText(st.getString("ultima_modificacion"));
                nombre = txt_nombre.getText().trim();
                capturista = 1;
               
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener los datos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        try {
        Connection cn1 = Conexion.conectar();
        PreparedStatement pst1 = cn1.prepareStatement(
                "select id_equipo, tipo_equipo, marca, estatus from equipo where id_cliente = '"+id_cliente+"'");
        ResultSet rs = pst1.executeQuery();
        table_equipos = new JTable(model);
        jScrollPane1.setViewportView(table_equipos);
         nombre = txt_nombre.getText().trim();
        model.addColumn("Id_equipo");
        model.addColumn("Tipo de equipo");
        model.addColumn("Marca");
        model.addColumn("Estatus");
        
        
            while (rs.next()) {    
                Object[] fila = new Object[4];
            for (int i = 0; i < 4; i++) {
                fila[i]=rs.getObject(i+1);
            }
            model.addRow(fila);
            }
            
            cn1.close();
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "No se pudo establecer conexion con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
                table_equipos.addMouseListener(new MouseAdapter() {
            @Override
        public void mouseClicked(MouseEvent e){
            int fila_point = table_equipos.rowAtPoint(e.getPoint());
            int columna_point = 0;
            if (fila_point>-1) {
                equipo =(int)model.getValueAt(fila_point, columna_point);
                    new Informacion_equipo().setVisible(true);
                    
                    
            }
        }
        });
        
        
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ultimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_equipos = new javax.swing.JTable();
        boton_registrar = new javax.swing.JButton();
        boton_actualizar = new javax.swing.JButton();
        boton_imprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Informacion del cliente ");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txt_telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txt_direccion.setBackground(new java.awt.Color(153, 153, 255));
        txt_direccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        txt_direccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ultima modificacion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txt_ultimo.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ultimo.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultimo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 30));

        table_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_equipos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 60, 380, 210));

        boton_registrar.setBackground(new java.awt.Color(153, 153, 255));
        boton_registrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_registrar.setText("Registar Equipo");
        boton_registrar.setBorder(null);
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, 30));

        boton_actualizar.setBackground(new java.awt.Color(153, 153, 255));
        boton_actualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        boton_actualizar.setText("Actualizar Cliente");
        boton_actualizar.setBorder(null);
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 200, 30));

        boton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        getContentPane().add(boton_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 120, 100));

        jLabel1.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
        nombre = txt_nombre.getText().trim();
        mail = txt_email.getText().trim();
        telefono = txt_telefono.getText().trim();
        direcion = txt_direccion.getText().trim();        
        validacion=0;
        if (nombre.isEmpty()) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }if (mail.isEmpty()) {
            txt_email.setBackground(Color.red);
            validacion++;
        }if (telefono.isEmpty()) {
            txt_telefono.setBackground(Color.red);
            validacion++;
        }if (direcion.isEmpty()) {
            txt_direccion.setBackground(Color.red);
            validacion++;
        }
        if (validacion ==0) {
            Connection cn = Conexion.conectar();
            try {
                PreparedStatement pst = cn.prepareStatement(
                "update clientes set nombre_cliente = ? ,email_cliente = ? , tel_cliente = ? , dir_cliente = ?,ultima_modificacion = ? where id_cliente = '"
                +id_cliente+"'");
                pst.setString(1, nombre);
                pst.setString(2, mail);
                pst.setString(3, telefono);
                pst.setString(4, direcion);
                pst.setString(5, Login.user);
                pst.executeUpdate();
                cn.close();
                 nombre = txt_nombre.getText().trim();
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al actualizar la informacion, contacte a el administrador","error",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "llene todos los campos","error",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_boton_actualizarActionPerformed

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed
        new registrar_equipo().setVisible(true);
    }//GEN-LAST:event_boton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_imprimir;
    private javax.swing.JButton boton_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_wall;
    private javax.swing.JTable table_equipos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_ultimo;
    // End of variables declaration//GEN-END:variables
}
