/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class InformacionEmpleado extends javax.swing.JFrame {
    String user = Admin_Usuarios.user_update;
    public static String ID;
    /**
     * Creates new form InformacionEmpleado
     */
    public InformacionEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Informacion del empleado");
        setSize(610, 440);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(wallpaper.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(), Image.SCALE_DEFAULT));
        label_wall.setIcon(wall);
        jLabel1.setText("Informacion de el empleado " + user );
        txt_registrado.setEnabled(false);
        try {
            
        //este codigo es para obtener y poner en los jTextField los diferentes datos de el usuario seleccionado
        Connection cn =Conexion.conectar();
        PreparedStatement pst = cn.prepareStatement(
                "select id_empleado, nombre_empleado, Email, Telefono, tipo_nivel, estatus, registrado_por from empleados where username = '"
        +user +"'");
        ResultSet rs =pst.executeQuery();
            if (rs.next()) {
                //esto es la declaracion de que se ponga lo que hay dentro de la base de datos en los diferrentes JTextField
                txt_nombre.setText(rs.getString("nombre_empleado"));
                txt_email.setText(rs.getString("Email"));
                txt_telefono.setText(rs.getString("Telefono"));
                txt_user.setText(user);
                txt_registrado.setText(rs.getString("registrado_por"));
                ID = rs.getString("id_empleado");
                
                box_permisos.setSelectedItem(rs.getString("tipo_nivel"));
                box_actividad.setSelectedItem(rs.getString("estatus"));
                
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error al obtener los datos.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        box_permisos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        box_actividad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_registrado = new javax.swing.JTextField();
        boton_actualizar = new javax.swing.JButton();
        boton_restablecer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion Del Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        txt_telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Permisos de:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        box_permisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista","Tecnico" }));
        box_permisos.setBorder(null);
        getContentPane().add(box_permisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        txt_user.setBackground(new java.awt.Color(153, 153, 255));
        txt_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 200, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estatus:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        box_actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        box_actividad.setBorder(null);
        getContentPane().add(box_actividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 90, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registrado por:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        txt_registrado.setBackground(new java.awt.Color(153, 153, 255));
        txt_registrado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_registrado.setForeground(new java.awt.Color(255, 255, 255));
        txt_registrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 200, 30));

        boton_actualizar.setBackground(new java.awt.Color(153, 153, 255));
        boton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        boton_actualizar.setText("Actuallizar Usuario");
        boton_actualizar.setBorder(null);
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 200, 40));

        boton_restablecer.setBackground(new java.awt.Color(153, 153, 255));
        boton_restablecer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_restablecer.setForeground(new java.awt.Color(255, 255, 255));
        boton_restablecer.setText("Restablecer Contraseña");
        boton_restablecer.setBorder(null);
        boton_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_restablecerActionPerformed(evt);
            }
        });
        getContentPane().add(boton_restablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 200, 40));

        jLabel9.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
        //esta es la declaracion de variables y asimismo sus valores
        int  permisos_cmb, estatus_cmb,validacion =0;
        String nombre, mail, telefono, pass, username, permisos_string ="",estatus_string= "";
        mail = txt_email.getText().trim();
        username = txt_user.getText().trim();
        nombre = txt_nombre.getText().trim();
        telefono = txt_telefono.getText().trim();
        permisos_cmb = box_permisos.getSelectedIndex() + 1 ;
        estatus_cmb = box_actividad.getSelectedIndex()+1;
        //esto comprueba si los diferentes campos estan vacios y si lo estan advierten a el usuario de esto
        if (mail.isEmpty()) {
            txt_email.setBackground(Color.red);
            validacion++;
        } if(username.isEmpty()) {
            txt_user.setBackground(Color.red);
            validacion++;
        }if(nombre.isEmpty()) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }
        if(telefono.isEmpty()) {
            txt_telefono.setBackground(Color.red);
            validacion++;
        }
        //esto quiere decir que si la variable validacion no incremento entonces que siga con el codigo como se debe
        //y si incremento por un campo vacio entonces advertir a el usuario de esto
        if (validacion == 0) {
            
            if(permisos_cmb == 1){
                permisos_string = "Administrador";
            }else if(permisos_cmb == 2){
                permisos_string = "Capturista";
            }else if(permisos_cmb == 3){
                permisos_string = "Tecnico";
            }
            if(estatus_cmb == 1){
                estatus_string = "Activo";
            }else if(estatus_cmb == 2){
                estatus_string = "Inactivo";
            }
            //esto establece que si un nombre de usuario esta ocupado en la base de datos advierte al usuario de que esto esta pasando
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                "select username from empleados where username = '"+username +"' and not id_empleado = '"+ID+"'");
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    
                    txt_user.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Este nombre de usuario esta ocupado","Error",JOptionPane.ERROR_MESSAGE);
                    cn.close();
                    //esto es si no se cumple que haya un nombre de usuario repetido entonces que ingrese correctamente a el usuario
                }else{
                    //esta es una conexion que le dice a la base de datos que actualizara los datos
                    Connection cn2 =Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "update empleados set nombre_empleado=?, Email=?, Telefono=?, username=?, tipo_nivel=?, estatus=? "
                          + "where id_empleado = '" + ID +"'");
                    //esto es la modificacion de los datos a la base de datos
                    pst2.setString(1,nombre);
                    pst2.setString(2,mail);
                    pst2.setString(3,telefono);
                    pst2.setString(4,username);
                    pst2.setString(5,permisos_string);
                    pst2.setString(6,estatus_string);
                    //esto es para que se ejecute la actualizacion y por ultimo que se cierre la conexion despues de la operacion
                    pst2.executeUpdate();
                    cn2.close();
                    
                    JOptionPane.showMessageDialog(null, "Modificacion exitosa", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e) {
                System.err.println("error al actualizar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "rellena todos los campos","error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_actualizarActionPerformed

    private void boton_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_restablecerActionPerformed
        new CambiarContraseña().setVisible(true);
    }//GEN-LAST:event_boton_restablecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_restablecer;
    private javax.swing.JComboBox<String> box_actividad;
    private javax.swing.JComboBox<String> box_permisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_wall;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_registrado;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
