/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class Login extends javax.swing.JFrame {

    //variable para poder enviar datos entre clases
    public static String user = "";
    //variable para poder guardar la contraseña de forma temporal
    private String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //la declaracion de diseño de el Jframe
        setSize(400, 550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);

        //Esto es el fondo que hay en la interfaz
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //Como se escalo este mismo
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(label_fondo.getWidth(), label_fondo.getHeight(), Image.SCALE_DEFAULT));
        label_fondo.setIcon(icono);
        this.repaint();

        //esto es el logo y su metodo de insersion
        ImageIcon logo = new ImageIcon("src/images/DS.png");
        //este codigo es como se escalo
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(label_logo.getWidth(), label_logo.getHeight(), Image.SCALE_SMOOTH));
        label_logo.setIcon(icono_logo);

    }

    
    //esto es para poner el logo de la app y poder hacer que se vea tanto en la esquina superior izquierda
    //como en la barra de tareas
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        label_logo = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        label_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setBackground(new java.awt.Color(153, 153, 255));
        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 30));

        ingresar.setBackground(new java.awt.Color(102, 102, 255));
        ingresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.setBorder(null);
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 280, 40));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 280, 30));
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 270));

        Creditos.setText("Creado Por Santiago Sierra");
        getContentPane().add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));
        getContentPane().add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //esto es la logica para poder iniciar sesion
    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed

        user = txt_usuario.getText().trim();
        pass = txt_password.getText().trim();

        //esta estructura es para validar que no se dejen espacios vacios
        if (!user.isEmpty() && !pass.isEmpty()) {

            try {
                //esto es una llamada a el metodo de conexion para no escribir todo el codigo de la conexion
                //con la base de datos
                Connection cn = Conexion.conectar();
                //esta linea sirve para hacer una llamada a la tabla empleados para que consiga la variable estatus y tipo
                //de nivel donde el nombre y la contraseña corresponden a las que se ingresaron
                PreparedStatement pst = cn.prepareStatement(
                   "select tipo_nivel , estatus from empleados where username = '" + user
                        + "' and password = '" + pass + "'");
                
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    //este codigo verifica cual es el nivel dentro de el negocio y dependiendo de eso lo envia a una interfaz
                    //o a otra
                    String tipo_nivel =rs.getString("tipo_nivel");
                    String estatus = rs.getString("estatus");
                    if (estatus.equals("Activo")) {
                    if (tipo_nivel.equals("Administrador")) {
                        dispose();
                        new Administrador().setVisible(true);
                    } else if (tipo_nivel.equals("Capturista")){
                        dispose();
                        new Capturista().setVisible(true);
                    }else if(tipo_nivel.equals("Tecnico")){
                        dispose();
                        new Tecnico().setVisible(true);
                    }}
                } else {
                    //esto indica que si los datos osea el usuario y la contraseña no son correctos entonces mandara a el usuario
                    //un mensaje para avisarle
                    JOptionPane.showMessageDialog(null, "Datos de Acceso Incorrectos");
                    txt_usuario.setText("");
                    txt_password.setText("");
                }
                
            } catch (SQLException e) {
                //esto notifica si por alguna razon el boton tiene problemas
                System.err.println("Error en el boton Acceder."+e);
                JOptionPane.showMessageDialog(null, "error al iniciar sesion, notifique al administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "debes rellenar todos los campos");
        }

    }//GEN-LAST:event_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creditos;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_logo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
