/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class registrar_equipo extends javax.swing.JFrame {
  InformacionCliente mensajero = new InformacionCliente();
  String nombre = mensajero.nombre;
  String id_cliente = mensajero.id_cliente;
  String modelo,serie,tipo, marca, observaciones, empleado;
  Calendar calen = Calendar.getInstance();
  String dia = Integer.toString(calen.get(Calendar.DATE));
  String mes = Integer.toString(calen.get(Calendar.MONTH));
  String annio = Integer.toString(calen.get(Calendar.YEAR));
  
    
    /**
     * Creates new form registrar_equipo
     */
    public registrar_equipo() {
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(630,410);
        setTitle("Registrar equipo");
        txt_nombre.setEnabled(false);
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wall = new ImageIcon(fondo.getImage().getScaledInstance(label_wall.getWidth(),label_wall.getHeight(),Image.SCALE_DEFAULT));
        label_wall.setIcon(wall);
        txt_nombre.setText(nombre);
        
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones_Cap = new javax.swing.JTextArea();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        box_tipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        box_marca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        boton_registrar = new javax.swing.JButton();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daño reportado y observaciones:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        observaciones_Cap.setColumns(20);
        observaciones_Cap.setRows(5);
        jScrollPane1.setViewportView(observaciones_Cap);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 340, 220));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de equipo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        box_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laptop", "desktop", "impresora", "multifuncional" }));
        box_tipo.setBorder(null);
        getContentPane().add(box_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        box_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "acer", "brother", "samsung", "epson" , "hp", "toshiba", "lg", "apple" }));
        box_marca.setBorder(null);
        getContentPane().add(box_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de serie:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txt_serie.setBackground(new java.awt.Color(153, 153, 255));
        txt_serie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_serie.setForeground(new java.awt.Color(255, 255, 255));
        txt_serie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, 30));

        jLabel8.setText("Creado por Santiago Sierra");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        boton_registrar.setBackground(new java.awt.Color(153, 153, 255));
        boton_registrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_registrar.setText("Registar Equipo");
        boton_registrar.setBorder(null);
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 210, 40));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed
        modelo = txt_modelo.getText().trim();
        serie = txt_serie.getText().trim();
        tipo = box_tipo.getSelectedItem().toString();
        marca = box_marca.getSelectedItem().toString();
        observaciones = observaciones_Cap.getText().trim();
        empleado = Login.user;
        if(!modelo.isEmpty()&&!serie.isEmpty()&&!observaciones.isEmpty()){
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "insert into equipo values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, id_cliente);
            pst.setString(3, tipo);
            pst.setString(4, marca);
            pst.setString(5, modelo);
            pst.setString(6, serie);
            pst.setString(7, dia);
            pst.setString(8, mes);
            pst.setString(9, annio);
            pst.setString(10, observaciones);
            pst.setString(11, "Nuevo Ingreso");
            pst.setString(12,empleado);
            pst.setString(13, " ");
            pst.setString(14, "");
            pst.executeUpdate();
            cn.close();
            txt_modelo.setText("");
            txt_nombre.setText("");
            txt_serie.setText("");
            observaciones_Cap.setText("");
            JOptionPane.showMessageDialog(null, "Los datos fueron Ingresados correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error con la conexion a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }else{
            if (modelo.isEmpty()) {
                txt_modelo.setBackground(Color.red);
            }if (serie.isEmpty()) {
                txt_serie.setBackground(Color.red);
            }if(observaciones.isEmpty()){
                observaciones_Cap.setText("no hay observaciones");
            }
            JOptionPane.showMessageDialog(null, "Campos Vacios", "error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrar_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrar_equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_registrar;
    private javax.swing.JComboBox<String> box_marca;
    private javax.swing.JComboBox<String> box_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_wall;
    private javax.swing.JTextArea observaciones_Cap;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_serie;
    // End of variables declaration//GEN-END:variables
}
