/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author santi
 */
public class Tecnico extends javax.swing.JFrame {
    String usuario = Login.user;
    int sesion_usuario;
    /**
     * Creates new form Tecnico
     */
    public Tecnico() {
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tecnico");
        setSize(550,260);
        setResizable(false);
        sesion_usuario = Administrador.sesion_usuario;
        ImageIcon wall = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon wallpaper = new ImageIcon(wall.getImage().getScaledInstance(label_wall.getWidth(), label_wall.getHeight(),Image.SCALE_DEFAULT));
        label_wall.setIcon(wallpaper);
        label_Bienvenida.setText("Bienvenido "+usuario);
        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        }else{
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Bienvenida = new javax.swing.JLabel();
        boton_equipos = new javax.swing.JButton();
        boton_grafica = new javax.swing.JButton();
        boton_graficaventas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Bienvenida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_Bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        label_Bienvenida.setText("Bienvenido");
        getContentPane().add(label_Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 540, 30));

        boton_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        boton_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_equiposActionPerformed(evt);
            }
        });
        getContentPane().add(boton_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 100));

        boton_grafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        getContentPane().add(boton_grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, 100));

        boton_graficaventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafica.png"))); // NOI18N
        getContentPane().add(boton_graficaventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 120, 100));

        jLabel1.setText("Gestion de Equipos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel2.setText("Grafica de estatus");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel3.setText("Grafica de marcas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel4.setText("Creado por Satiago Sierra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        getContentPane().add(label_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_equiposActionPerformed
        new Gestion_Equipos().setVisible(true);
    }//GEN-LAST:event_boton_equiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_equipos;
    private javax.swing.JButton boton_grafica;
    private javax.swing.JButton boton_graficaventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_Bienvenida;
    private javax.swing.JLabel label_wall;
    // End of variables declaration//GEN-END:variables
}
